# .github/workflows/echo-hello-world.yml
name: Echo Hello World

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo-hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo Hello World
      run: echo "Hello World"
