# .github/workflows/test-oidc-get.yml
name: Test OIDC GET Request

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # enable OIDC token issuance
  contents: read    # allows checkout (not strictly needed here)

jobs:
  oidc-get:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      API_URL: https://<your-app-name>.azurewebsites.net/validate  # 🔁 replace with your GET endpoint

    steps:
      - name: 🔐 Request OIDC token from GitHub
        id: fetch_token
        run: |
          echo "🌐 Requesting OIDC token..."
          raw=$(curl -s \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api://${CLIENT_ID}")
          echo "🔁 Raw token response JSON: $raw"
          token=$(echo "$raw" | jq -r '.value')
          echo "✔️ Token length: ${#token}"
          echo "TOKEN=$token" >> $GITHUB_ENV

      - name: 📡 Send GET request with Bearer token
        run: |
          echo "🚀 Sending GET to $API_URL"
          response=$(curl -s -H "Authorization: Bearer $TOKEN" "$API_URL")
          echo "🔍 Response JSON:"
          echo "$response" | jq .
