name: Test OIDC GET Request

on:
  push:
    branches:
      - main

permissions:
  id-token: write   
  contents: read    

jobs:
  oidc-get:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

    steps:
      - name: 🔐 Request OIDC token from GitHub
        id: fetch_token
        run: |
          echo "🌐 Requesting OIDC token..."
          raw=$(curl -s \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api://${CLIENT_ID}")
          echo "🔁 Raw token response JSON: $raw"
          token=$(echo "$raw" | jq -r '.value')
          echo "✔️ Token length: ${#token}"
          echo "TOKEN=$token" >> $GITHUB_ENV

      - name: 📡 Send GET request to prod
        run: |
          echo "🚀 Sending GET to https://sentinel-content-validationapi-prod-bvgsc3hjhyeqangg.canadacentral-01.azurewebsites.net/ "
          response=$(curl -s -H "Authorization: Bearer $TOKEN" "https://sentinel-content-validationapi-prod-bvgsc3hjhyeqangg.canadacentral-01.azurewebsites.net/ ")
          echo "🔍 Response JSON:"
          echo "$response" | jq .

      - name: 📡 Send GET request too dev 
        run: |
          echo "🚀 Sending GET to dev"
          response=$(curl -s -H "Authorization: Bearer $TOKEN" "https://sentintel-content-dev-fue4ashcg9fnfge9.canadacentral-01.azurewebsites.net/")
          echo "🔍 Response JSON:"
          echo "$response" | jq .
        
