# .github/workflows/get-oidc-token-preview.yml
name: Preview OIDC Token

on:
  push:
    branches:
      - main

permissions:
  id-token: write    # enable OIDC
  contents: read     # not strictly needed here

jobs:
  preview-token:
    runs-on: ubuntu-latest

    env:
      CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

    steps:
      - name: Request OIDC token via curl
        id: fetch
        run: |
          echo "🌐 Requesting OIDC token from GitHub’s ID endpoint"
          response=$(curl -s \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api://${CLIENT_ID}")
          token=$(echo "$response" | jq -r '.value')
          # print first 10 chars
          echo "Token starts with: ${token:0:10}..."
